app/app.global.scss
app/components/DropZone.js
app/components/DropZone.scss
app/components/LabRecordImportWizard.scss
app/components/NavBar.js
app/components/NavBar.scss
app/components/PatientIdStep.js
app/components/Table.scss
app/components/WizardHeader.scss
app/containers/App.js
app/material-overrides.scss

General layout enhancements

---

app/actions/sites.js
app/app.global.scss
app/components/LabRecordsDetailList.js
app/components/PatientEntriesList.js
app/components/Sites.js
app/components/Table.js
app/components/Table.scss
app/constants/config.js
app/reducers/sites.js

60: <Sites /> search and filtering

---

app/components/AntibioticList.js
app/components/Sites.js

74: Filtering <AntibioticsList />

---

app/actions/patient.js
app/actions/patients.js
app/components/PatientsDialogForm.js
app/components/PatientsForm.js
app/components/PatientsList.js
app/containers/PatientsIndex.js

Closes #88. Edit patients

---

app/components/LabRecordImportWizard.scss
app/components/ProtectedHealthInformationStep.js

65: Implement names for radio buttons

---

app/components/LabRecordsDetailList.js

68: Add filtering for <LabRecordsDetailList />

---

app/actions/antibioticConsumptionStats.js
app/actions/antibiotics.js
app/actions/clinicalServices.js
app/actions/cultureTypes.js
app/actions/patients.js
app/actions/specimenSources.js
app/actions/sync.js

...upon synchronization update, which breaks app consistency

Fixes #118 - Remote ids overwrite local ids

---

app/components/Sites.js

Fix search conditions for <Sites/>

---

app/components/LabRecordsDetailList.js
app/components/LabRecordsDetailList.scss

Add emphasis to LabRecordId and PatientId on <LabRecordsDetailList/>

---

app/actions/sync.js

Fixed infinite sync loop

---

app/components/AntibioticList.js

Added packsize column

---

app/components/ProtectedHealthInformationStep.js

Added new date formats & fixed old ones

---

app/components/DropZone.js
app/components/DropZone.scss
app/components/ElectronicPharmacyStockRecordImportWizard.js
app/static/electronicPharmacyRecordsTemplate.csv
package.json

Added template file for pharmacy records

---

app/actions/antibioticConsumptionStats.js
app/actions/sync.js
app/db/migrations/004_addDeletedAtToStockMovements.js
app/models/antibioticConsumptionStat.js

This reverts commit 263571f6dc813e8adaa0e995e60a7c9bde8df263.

Added soft delete to antibiotic consumption stats

---

app/components/DropZone.js
app/components/ErrorMessage.js
app/components/ErrorMessage.scss
package.json
yarn.lock

Added validation for format

---

app/components/DropZone.js
app/components/ErrorMessage.js
app/components/ErrorMessage.scss
package.json
yarn.lock

Reverts instedd/maap-collector#258

Revert "Added validation for format"

---

app/components/DropZone.js
app/components/ErrorMessage.js
app/components/ErrorMessage.scss
package.json
yarn.lock

Reverts instedd/maap-collector#259

Revert "Revert "Added validation for format""

---

app/actions/electronicPharmacyStockRecords.js
app/actions/labRecords.js
app/utils/attachments.js

Changes in the server (in case they're necessary):
https://github.com/instedd/maap-store/pull/73

#276 JSON attributes as attachments

---

app/actions/electronicPharmacyStockRecords.js
app/actions/labRecords.js
app/actions/sync.js

For #310
Replace `forEach` with `Promise.all` to enforce requests completion
@pyritewolf, I added you as `reviewer` so you can review the general approach to solve this issue, that is using `Promise.all` as I mentioned in the commit

Force requests to complete on syncing

---

app/components/Sites.js

Display remote Site IDs instead of local ones
